### ISSUE TITLE
onnx vs pth performance

### ISSUE THREAD

**Issue by JaouadROS** [fabio-sim/LightGlue-ONNX#88] opened 2024-09-15 17:08 UTC
Thank you for sharing this work.

I'm trying to use your `superpoint_lightglue.onnx` in `C++` for matching but I don't get the same results as from the `*.pth` version. I've attached the raw images if you want to test the matching on your side. What could be the issue? Have you tried `Torch Script`?

I didn't compare the features detection but I do get many of them so I think the features detection is working.

Using *.pth inference in python
![image](https://github.com/user-attachments/assets/b3005402-5ce5-4d44-9d3e-37dcd6ef0f83)

Using onnx in  C++ inference
![matches_screenshot_15 09 2024](https://github.com/user-attachments/assets/8feee6bb-c634-4919-90ff-48d035fd5d88)

Here are the raw images:

![Snap_Pic_4_c](https://github.com/user-attachments/assets/7d104970-503f-4ba4-add0-eb76f94b096a)
![Snap_Pic_5_c](https://github.com/user-attachments/assets/a1b7f2d4-dbc1-4dbf-a792-2c4ea2a4bd30)

**Comment by fabio-sim** [comment] 2024-09-17 13:27
Hi @JaouadROS, thank you for your interest in LightGlue-ONNX.

I appreciate the input images. I tried to reproduce the matching using the following command:

```console
python dynamo.py infer weights/superpoint_lightglue_pipeline.onnx data/left.png data/right.png superpoint -o matches.png -h 1944 -w 924 -d cuda
```

These are the matches I got for different numbers of keypoints:

| 1024 | 2048 | 4096 |
| --- | --- | --- |
| ![matches_1024](https://github.com/user-attachments/assets/69a92964-f9fd-4266-9956-195622e9e4bd) | ![matches_2048](https://github.com/user-attachments/assets/dd0443cc-bc65-4509-a599-493ac64104bf) | ![matches_4096](https://github.com/user-attachments/assets/254922d1-3a46-45df-b217-46dc0a0d1a6d) |

The difference from the torch version is due to differing implementations.

As for TorchScript, in theory it should work since the ONNX export succeeds (and the exporter is based on TorchScript).

**Comment by JaouadROS** [comment] 2024-09-17 18:08
Thank you for the quick reply.

I see that you're using the fused version, should I get the same results if I use detection and matching separately? in my case, only the matching is failing.

When checking your inference scripts in `dynamo.py` or `infer.py` I see only one inference session created, so it doesn't supports loading two models, one for features and the other for matching so I can test them separately, right?

**Comment by fabio-sim** [comment] 2024-09-18 11:52
Yes, I'm using the merged pipeline here: https://github.com/fabio-sim/LightGlue-ONNX/releases/download/v2.0/superpoint_lightglue_pipeline.onnx. Inside, it really just executes both parts sequentially:

https://github.com/fabio-sim/LightGlue-ONNX/blob/00cdd6a800aeea3008ddb08c0efafcd0abe6f3b7/lightglue_dynamo/models/pipeline.py#L1-L22

I found it to be quite the hassle having to export and maintain separate inference sessions, but I believe you can find some example code used by the older `infer.py` script to load two sessions here:

https://github.com/fabio-sim/LightGlue-ONNX/blob/00cdd6a800aeea3008ddb08c0efafcd0abe6f3b7/onnx_runner/lightglue.py#L5-L23

**Closed** 2024-09-19 08:52 UTC
